modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/TheIllusiveC4/Polymorph/issues"
logoFile="${mod_icon}"
logoBlur=false
license="LGPL-3.0-or-later"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_url}"
authors="${mod_author}"
description='''
${mod_description}
'''
[[dependencies.polymorph]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.polymorph]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.polymorph]]
    modId="fastbench"
    mandatory=false
    versionRange="[4.6.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.polymorph]]
    modId="fastfurnace"
    mandatory=false
    versionRange="[4.5.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.polymorph]]
    modId="sophisticatedbackpacks"
    mandatory=false
    versionRange="[1.16.5-3.15.0,)"
    ordering="NONE"
    side="BOTH"
