modLoader="javafml"
loaderVersion="[1,)"
license="${license}"
logoBlur=false
issueTrackerURL="${issues_url}"
logoFile="${mod_id}_icon.png"
[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_name}"
    displayURL = "${sources_url}"
    authors="${mod_author}"
    description='''
    ${description}
    '''
[[mixins]]
    config = "${mod_id}.mixins.json"
[[dependencies.polymorph]]
    modId="neoforge"
    mandatory=true
    versionRange="${neoforge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.polymorph]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
